import{a as E,S,i as d}from"./assets/vendor-C4-ZuMk8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();const q="47115642-a97741713bebc955e7d8d0e17",M="https://pixabay.com/api/";async function g(e,t=1,i=15){try{return(await E.get(M,{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:i}})).data}catch(n){throw console.error("Error fetching images:",n),n}}const h=document.querySelector(".gallery");let $=new S(".gallery a");function p(e){const t=e.map(({webformatURL:i,largeImageURL:n,tags:r,likes:o,views:c,comments:v,downloads:P})=>`
        <div class="gallery__item">
          <a href="${n}">
            <img src="${i}" alt="${r}" loading="lazy" />
          </a>
          <div class="photo-info">
            <p><b>Likes:</b> ${o}</p>
            <p><b>Views:</b> ${c}</p>
            <p><b>Comments:</b> ${v}</p>
            <p><b>Downloads:</b> ${P}</p>
          </div>
        </div>
      `).join("");h.insertAdjacentHTML("beforeend",t),$.refresh()}function A(){h.innerHTML=""}function f(e){e.classList.add("is-hidden")}function y(e){e.classList.remove("is-hidden")}function B(){const{height:e}=document.querySelector(".gallery").getBoundingClientRect();window.scrollBy({top:e*.7,behavior:"smooth"})}const N=document.querySelector("#search-form"),s=document.querySelector("#load-more-btn"),b=document.querySelector("#loader");let l="",a=1;const u=15;let m=0;N.addEventListener("submit",O);s.addEventListener("click",_);function L(){b.classList.remove("is-hidden")}function w(){b.classList.add("is-hidden")}async function O(e){if(e.preventDefault(),l=e.currentTarget.elements.searchQuery.value.trim(),!!l){a=1,A(),f(s),L();try{const{hits:t,totalHits:i}=await g(l,a,u);if(m=i,t.length===0){d.warning({title:"Warning",message:"No images found. Please try another query."});return}p(t),a*u<m&&y(s)}catch(t){d.error({title:"Error",message:t.message.includes("Network")?"Network error! Please check your internet connection.":"An unexpected error occurred. Please try again later."}),console.error("Error loading images:",t)}finally{w()}}}async function _(){a+=1,f(s),L();try{const{hits:e}=await g(l,a,u);p(e),a*u>=m?(f(s),d.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):(y(s),B())}catch(e){d.error({title:"Error",message:"An error occurred while loading more images. Please try again later."}),console.error("Error loading more images:",e)}finally{w()}}
//# sourceMappingURL=index.js.map
